// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwu8HUrotP0CHDwvo3usQ8R8NZUVJ7Wc',
    appId: '1:787659069742:web:dc6a871459ae0665d982bf',
    messagingSenderId: '787659069742',
    projectId: 'assignment-9fadb',
    authDomain: 'assignment-9fadb.firebaseapp.com',
    storageBucket: 'assignment-9fadb.appspot.com',
    measurementId: 'G-S94B0YKSX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBFdDMHaPsVaYCnXwcoa-8CwQMOn-kUM',
    appId: '1:787659069742:android:2a13ccdbe24bdcbad982bf',
    messagingSenderId: '787659069742',
    projectId: 'assignment-9fadb',
    storageBucket: 'assignment-9fadb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9t_736jZVAFFTnhnYz9zw9ZzYGm9n5MU',
    appId: '1:787659069742:ios:039cfa5b2d5652b5d982bf',
    messagingSenderId: '787659069742',
    projectId: 'assignment-9fadb',
    storageBucket: 'assignment-9fadb.appspot.com',
    androidClientId: '787659069742-160l4aeep8kc0iif83ivdj16ej3da8qp.apps.googleusercontent.com',
    iosClientId: '787659069742-jb98tcmv8b4lpp0hvjrvaim9olv7ppht.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9t_736jZVAFFTnhnYz9zw9ZzYGm9n5MU',
    appId: '1:787659069742:ios:b9297ea49ffc2901d982bf',
    messagingSenderId: '787659069742',
    projectId: 'assignment-9fadb',
    storageBucket: 'assignment-9fadb.appspot.com',
    androidClientId: '787659069742-160l4aeep8kc0iif83ivdj16ej3da8qp.apps.googleusercontent.com',
    iosClientId: '787659069742-bft5drgp1i2qsad2tfvj50pot3de9prs.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
